DROP TABLE IF EXISTS TB_MEMBER;

CREATE TABLE TB_MEMBER (
    `ID` NUMBER AUTO_INCREMENT NOT NULL,
    `NAME` VARCHAR NOT NULL,
    `PHONE_NUMBER` VARCHAR NOT NULL,
    PRIMARY KEY (`ID`)
);

ALTER TABLE TB_MEMBER ADD CONSTRAINT MEMBER_UNIQUE UNIQUE (NAME, PHONE_NUMBER);