server:
  port: 9091

spring:
  application:
    name: msa-architecture-turbine

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8170/eureka/
  instance:
    prefer-ip-address: true

turbine:
  aggregator:
    cluster-config: SYSTEM, USER
  app-config: ${msa.coffee.application}
  cluster-name-expression: metadata['cluster']

#  app-config: MSA-COFFEE-MEMBER
#  cluster-name-expression: new String("default")

#  aggregator:
#    cluster-config: ${msa.coffee.application}
#  app-config: ${msa.coffee.application}

msa:
  coffee:
    application: MSA-COFFEE-MEMBER, MSA-COFFEE-ORDER, MSA-COFFEE-STATUS
