server:
  port: 9091

spring:
  application:
    name: msa-architecture-turbine

eureka:
  client:
    service-url:
      defaultZone: http://localhost:/8170/eureka/
  instance:
    prefer-ip-address: true

