server:
  port: 8176

logging:
  level:
    org.springframework.jdbc: debug
    com.example.msa: debug

msa:
  coffee:
    member: msa-coffee-member

spring:
  application:
    name: msa-coffee-order

  profiles:
    include: chaos-monkey

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=1
    driver-class-name: org.h2.Driver
    username: sa
    password:
    sql-script-encoding: UTF-8

  h2:
    console:
      enabled: true

mybatis:
  type-aliases-package: com.example.msa.repository
  mapper-locations: classpath:sql/*.xml
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8170/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      cluster: USER

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL

management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, chaosmonkey, hystrix.stream

chaos:
  monkey:
    enabled: false
    watcher:
      repository: true
#      rest-controller: true
    assaults:
      level: 3
      latency-active: true
      latency-range-start: 3000
      latency-range-end: 6000
#    assaults:
#      watched-custom-services: com.example.msa.repository.OrderRepository, com.example.msa.rest.OrderRestController
